# Generated by Django 5.1.3 on 2024-11-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Changeset",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("max_lat", models.FloatField()),
                ("max_lon", models.FloatField()),
                ("min_lat", models.FloatField()),
                ("min_lon", models.FloatField()),
                ("uid", models.PositiveIntegerField(null=True)),
                ("display_name", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
