# Generated by Django 5.0.6 on 2024-05-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osm_changesets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changeset",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="changeset",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
