# Generated by Django 5.0.6 on 2024-05-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osm_changesets", "0002_alter_changeset_options_alter_changeset_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_name",
        ),
    ]
